### ISSUE TITLE
依赖的hetu-script和samsara_engine中缺少对应的方法

### ISSUE THREAD

**Issue by fuguohong1024** [hetu-script/heavenly-tribulation#1]
### fflutter及dart版本
```
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision a14f74ff3a (11 days ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3
```

pubspec.yaml中关于您其他项目的依赖我是直接下到本地的，分支均为master
![1717333691817](https://github.com/hetu-script/heavenly-tribulation/assets/48230693/7112d446-335c-4ba8-b680-3187874527c4)

flutter pub get之后，发现其他项目的版本好像跟您其他项目目前的master的版本不一致，存在多个方法不存在或者无此参数的情况
1. heavenly-tribulation\game\lib\state\game_save.dart:16
![1717333805951](https://github.com/hetu-script/heavenly-tribulation/assets/48230693/27eb482b-2452-4501-aff5-efd462afd41c)

2. heavenly-tribulation\game\lib\scene\world\animation\flying_sword.dart:29
![1717333848473](https://github.com/hetu-script/heavenly-tribulation/assets/48230693/08e358a8-82d0-4b88-bbac-8c2b894a2e6c)

3. heavenly-tribulation\game\lib\scene\battle\components\character.dart:429
![1717334025888](https://github.com/hetu-script/heavenly-tribulation/assets/48230693/23dd08b2-4b4f-49b4-af30-4c39cf36c4da)

4. heavenly-tribulation\game\lib\scene\battle\battle.dart:74 
![1717334074795](https://github.com/hetu-script/heavenly-tribulation/assets/48230693/a3872240-a9a3-4c6d-b541-fbd53535d52c)

请问我应该怎么去获取对应的版本或者修改呢？期待您的回复！

**Comment by hythl0day** [comment]
hetu_script 我用的不是master版本，是另一个分支，叫javascript那个。

这个游戏目前并不可玩，还在开发中。进去除了在大地图走走之外，基本什么也干不了。

目前只是一个框架而已。你最多看看代码参考下实现而已。

**Comment by fuguohong1024** [comment]
好的好的 谢谢大佬！
